SET DEFINE OFF

INSERT INTO DELIVERYMETHODS (DELIVERYMETHODID, DELIVERYMETHODNAME) 
VALUES (8, N'Air Freight');

INSERT INTO DELIVERYMETHODS (DELIVERYMETHODID, DELIVERYMETHODNAME) 
VALUES (5, N'Chilled Van');

INSERT INTO DELIVERYMETHODS (DELIVERYMETHODID, DELIVERYMETHODNAME) 
VALUES (2, N'Courier');

INSERT INTO DELIVERYMETHODS (DELIVERYMETHODID, DELIVERYMETHODNAME) 
VALUES (4, N'Customer Collect');

INSERT INTO DELIVERYMETHODS (DELIVERYMETHODID, DELIVERYMETHODNAME) 
VALUES (6, N'Customer Courier to Collect');

INSERT INTO DELIVERYMETHODS (DELIVERYMETHODID, DELIVERYMETHODNAME) 
VALUES (3, N'Delivery Van');

INSERT INTO DELIVERYMETHODS (DELIVERYMETHODID, DELIVERYMETHODNAME) 
VALUES (1, N'Post');

INSERT INTO DELIVERYMETHODS (DELIVERYMETHODID, DELIVERYMETHODNAME) 
VALUES (10, N'Refrigerated Air Freight');

INSERT INTO DELIVERYMETHODS (DELIVERYMETHODID, DELIVERYMETHODNAME) 
VALUES (9, N'Refrigerated Road Freight');

INSERT INTO DELIVERYMETHODS (DELIVERYMETHODID, DELIVERYMETHODNAME) 
VALUES (7, N'Road Freight');

