SET DEFINE OFF

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (1, N'Afghanistan', N'Islamic State of Afghanistan', N'AFG', 4, N'UN Member State', 28400000, N'Asia', N'Asia', N'Southern Asia');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (3, N'Albania', N'Republic of Albania', N'ALB', 8, N'UN Member State', 3785031, N'Europe', N'Europe', N'Southern Europe');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (4, N'Algeria', N'People''s Democratic Republic of Algeria', N'DZA', 12, N'UN Member State', 34178188, N'Africa', N'Africa', N'Northern Africa');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (6, N'Andorra', N'Principality of Andorra', N'AND', 20, N'UN Member State', 87243, N'Europe', N'Europe', N'Southern Europe');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (7, N'Angola', N'People''s Republic of Angola', N'AGO', 24, N'UN Member State', 12799293, N'Africa', N'Africa', N'Middle Africa');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (10, N'Antigua and Barb.', N'Antigua and Barbuda', N'ATG', 28, N'UN Member State', 85632, N'North America', N'Americas', N'Caribbean');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (11, N'Argentina', N'Argentine Republic', N'ARG', 32, N'UN Member State', 42550127, N'South America', N'Americas', N'South America');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (12, N'Armenia', N'Republic of Armenia', N'ARM', 51, N'UN Member State', 2967004, N'Asia', N'Asia', N'Western Asia');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (15, N'Australia', N'Commonwealth of Australia', N'AUS', 36, N'UN Member State', 22997671, N'Oceania', N'Oceania', N'Australia and New Zealand');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (16, N'Austria', N'Republic of Austria', N'AUT', 40, N'UN Member State', 8210281, N'Europe', N'Europe', N'Western Europe');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (17, N'Azerbaijan', N'Republic of Azerbaijan', N'AZE', 31, N'UN Member State', 8568218, N'Asia', N'Asia', N'Western Asia');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (18, N'Bahamas', N'Commonwealth of the Bahamas', N'BHS', 44, N'UN Member State', 309156, N'North America', N'Americas', N'Caribbean');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (19, N'Bahrain', N'Kingdom of Bahrain', N'BHR', 48, N'UN Member State', 727785, N'Asia', N'Asia', N'Western Asia');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (20, N'Bangladesh', N'People''s Republic of Bangladesh', N'BGD', 50, N'UN Member State', 156050883, N'Asia', N'Asia', N'Southern Asia');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (21, N'Barbados', N'Barbados', N'BRB', 52, N'UN Member State', 284589, N'North America', N'Americas', N'Caribbean');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (22, N'Belarus', N'Republic of Belarus', N'BLR', 112, N'UN Member State', 9648533, N'Europe', N'Europe', N'Eastern Europe');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (23, N'Belgium', N'Kingdom of Belgium', N'BEL', 56, N'UN Member State', 10830909, N'Europe', N'Europe', N'Western Europe');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (24, N'Belize', N'Belize', N'BLZ', 84, N'UN Member State', 307899, N'North America', N'Americas', N'Central America');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (25, N'Benin', N'Republic of Benin', N'BEN', 204, N'UN Member State', 8791832, N'Africa', N'Africa', N'Western Africa');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (27, N'Bhutan', N'Kingdom of Bhutan', N'BTN', 64, N'UN Member State', 691141, N'Asia', N'Asia', N'Southern Asia');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (28, N'Bolivia', N'Plurinational State of Bolivia', N'BOL', 68, N'UN Member State', 9775246, N'South America', N'Americas', N'South America');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (29, N'Bosnia and Herz.', N'Bosnia and Herzegovina', N'BIH', 70, N'UN Member State', 4797950, N'Europe', N'Europe', N'Southern Europe');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (30, N'Botswana', N'Republic of Botswana', N'BWA', 72, N'UN Member State', 2070511, N'Africa', N'Africa', N'Southern Africa');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (32, N'Brazil', N'Federative Republic of Brazil', N'BRA', 76, N'UN Member State', 198739269, N'South America', N'Americas', N'South America');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (34, N'Brunei', N'Negara Brunei Darussalam', N'BRN', 96, N'UN Member State', 388190, N'Asia', N'Asia', N'South-Eastern Asia');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (35, N'Bulgaria', N'Republic of Bulgaria', N'BGR', 100, N'UN Member State', 7204687, N'Europe', N'Europe', N'Eastern Europe');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (36, N'Burkina Faso', N'Burkina Faso', N'BFA', 854, N'UN Member State', 15746232, N'Africa', N'Africa', N'Western Africa');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (37, N'Burundi', N'Republic of Burundi', N'BDI', 108, N'UN Member State', 8988091, N'Africa', N'Africa', N'Eastern Africa');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (38, N'Cambodia', N'Kingdom of Cambodia', N'KHM', 116, N'UN Member State', 14494293, N'Asia', N'Asia', N'South-Eastern Asia');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (39, N'Cameroon', N'Republic of Cameroon', N'CMR', 120, N'UN Member State', 18879301, N'Africa', N'Africa', N'Middle Africa');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (40, N'Canada', N'Canada', N'CAN', 124, N'UN Member State', 34826696, N'North America', N'Americas', N'Northern America');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (43, N'Central African Rep.', N'Central African Republic', N'CAF', 140, N'UN Member State', 4511488, N'Africa', N'Africa', N'Middle Africa');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (44, N'Chad', N'Republic of Chad', N'TCD', 148, N'UN Member State', 10742376, N'Africa', N'Africa', N'Middle Africa');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (45, N'Chile', N'Republic of Chile', N'CHL', 152, N'UN Member State', 16601707, N'South America', N'Americas', N'South America');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (46, N'China', N'People''s Republic of China', N'CHN', 156, N'UN Member State', 1392157488, N'Asia', N'Asia', N'Eastern Asia');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (47, N'Colombia', N'Republic of Colombia', N'COL', 170, N'UN Member State', 45644023, N'South America', N'Americas', N'South America');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (48, N'Comoros', N'Union of the Comoros', N'COM', 174, N'UN Member State', 752438, N'Africa', N'Africa', N'Eastern Africa');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (49, N'Congo', N'Republic of Congo', N'COG', 178, N'UN Member State', 4012809, N'Africa', N'Africa', N'Middle Africa');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (51, N'Costa Rica', N'Republic of Costa Rica', N'CRI', 188, N'UN Member State', 4424032, N'North America', N'Americas', N'Central America');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (52, N'Côte d''Ivoire', N'Republic of Ivory Coast', N'CIV', 384, N'UN Member State', 21441750, N'Africa', N'Africa', N'Western Africa');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (53, N'Croatia', N'Republic of Croatia', N'HRV', 191, N'UN Member State', 4489409, N'Europe', N'Europe', N'Southern Europe');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (54, N'Cuba', N'Republic of Cuba', N'CUB', 192, N'UN Member State', 11451652, N'North America', N'Americas', N'Caribbean');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (56, N'Cyprus', N'Republic of Cyprus', N'CYP', 196, N'UN Member State', 531640, N'Asia', N'Asia', N'Western Asia');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (57, N'Czech Rep.', N'Czech Republic', N'CZE', 203, N'UN Member State', 10620380, N'Europe', N'Europe', N'Eastern Europe');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (58, N'Dem. Rep. Congo', N'Democratic Republic of the Congo', N'COD', 180, N'UN Member State', 68692542, N'Africa', N'Africa', N'Middle Africa');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (59, N'Dem. Rep. Korea', N'Democratic People''s Republic of Korea', N'PRK', 408, N'UN Member State', 22665345, N'Asia', N'Asia', N'Eastern Asia');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (60, N'Denmark', N'Kingdom of Denmark', N'DNK', 208, N'UN Member State', 5500510, N'Europe', N'Europe', N'Northern Europe');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (61, N'Djibouti', N'Republic of Djibouti', N'DJI', 262, N'UN Member State', 516055, N'Africa', N'Africa', N'Eastern Africa');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (62, N'Dominica', N'Commonwealth of Dominica', N'DMA', 212, N'UN Member State', 72660, N'North America', N'Americas', N'Caribbean');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (63, N'Dominican Rep.', N'Dominican Republic', N'DOM', 214, N'UN Member State', 9650054, N'North America', N'Americas', N'Caribbean');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (64, N'Ecuador', N'Republic of Ecuador', N'ECU', 218, N'UN Member State', 14573101, N'South America', N'Americas', N'South America');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (65, N'Egypt', N'Arab Republic of Egypt', N'EGY', 818, N'UN Member State', 83082869, N'Africa', N'Africa', N'Northern Africa');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (66, N'El Salvador', N'Republic of El Salvador', N'SLV', 222, N'UN Member State', 7185218, N'North America', N'Americas', N'Central America');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (67, N'Eq. Guinea', N'Republic of Equatorial Guinea', N'GNQ', 226, N'UN Member State', 676730, N'Africa', N'Africa', N'Middle Africa');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (68, N'Eritrea', N'State of Eritrea', N'ERI', 232, N'UN Member State', 5647168, N'Africa', N'Africa', N'Eastern Africa');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (69, N'Estonia', N'Republic of Estonia', N'EST', 233, N'UN Member State', 1299371, N'Europe', N'Europe', N'Northern Europe');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (70, N'Ethiopia', N'Federal Democratic Republic of Ethiopia', N'ETH', 231, N'UN Member State', 85237338, N'Africa', N'Africa', N'Eastern Africa');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (73, N'Fiji', N'Republic of Fiji', N'FJI', 242, N'UN Member State', 982508, N'Oceania', N'Oceania', N'Melanesia');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (74, N'Finland', N'Republic of Finland', N'FIN', 246, N'UN Member State', 5460286, N'Europe', N'Europe', N'Northern Europe');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (77, N'France', N'French Republic', N'FRA', 250, N'UN Member State', 64057792, N'Europe', N'Europe', N'Western Europe');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (78, N'Gabon', N'Gabonese Republic', N'GAB', 266, N'UN Member State', 1514993, N'Africa', N'Africa', N'Middle Africa');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (79, N'Gambia', N'Republic of the Gambia', N'GMB', 270, N'UN Member State', 1782893, N'Africa', N'Africa', N'Western Africa');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (80, N'Georgia', N'Georgia', N'GEO', 268, N'UN Member State', 4615807, N'Asia', N'Asia', N'Western Asia');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (81, N'Germany', N'Federal Republic of Germany', N'DEU', 276, N'UN Member State', 82329758, N'Europe', N'Europe', N'Western Europe');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (82, N'Ghana', N'Republic of Ghana', N'GHA', 288, N'UN Member State', 23832495, N'Africa', N'Africa', N'Western Africa');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (83, N'Greece', N'Hellenic Republic', N'GRC', 300, N'UN Member State', 10737428, N'Europe', N'Europe', N'Southern Europe');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (85, N'Grenada', N'Grenada', N'GRD', 308, N'UN Member State', 90739, N'North America', N'Americas', N'Caribbean');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (87, N'Guatemala', N'Republic of Guatemala', N'GTM', 320, N'UN Member State', 13276517, N'North America', N'Americas', N'Central America');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (89, N'Guinea', N'Republic of Guinea', N'GIN', 324, N'UN Member State', 10057975, N'Africa', N'Africa', N'Western Africa');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (90, N'Guinea-Bissau', N'Republic of Guinea-Bissau', N'GNB', 624, N'UN Member State', 1533964, N'Africa', N'Africa', N'Western Africa');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (91, N'Guyana', N'Co-operative Republic of Guyana', N'GUY', 328, N'UN Member State', 772298, N'South America', N'Americas', N'South America');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (92, N'Haiti', N'Republic of Haiti', N'HTI', 332, N'UN Member State', 9396957, N'North America', N'Americas', N'Caribbean');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (94, N'Honduras', N'Republic of Honduras', N'HND', 340, N'UN Member State', 8104568, N'North America', N'Americas', N'Central America');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (96, N'Hungary', N'Republic of Hungary', N'HUN', 348, N'UN Member State', 9905596, N'Europe', N'Europe', N'Eastern Europe');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (97, N'Iceland', N'Republic of Iceland', N'ISL', 352, N'UN Member State', 306694, N'Europe', N'Europe', N'Northern Europe');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (98, N'India', N'Republic of India', N'IND', 356, N'UN Member State', 1166079220, N'Asia', N'Asia', N'Southern Asia');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (100, N'Indonesia', N'Republic of Indonesia', N'IDN', 360, N'UN Member State', 240271522, N'Asia', N'Asia', N'South-Eastern Asia');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (101, N'Iran', N'Islamic Republic of Iran', N'IRN', 364, N'UN Member State', 66429284, N'Asia', N'Asia', N'Southern Asia');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (102, N'Iraq', N'Republic of Iraq', N'IRQ', 368, N'UN Member State', 31129225, N'Asia', N'Asia', N'Western Asia');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (103, N'Ireland', N'Ireland', N'IRL', 372, N'UN Member State', 4203200, N'Europe', N'Europe', N'Northern Europe');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (105, N'Israel', N'State of Israel', N'ISR', 376, N'UN Member State', 7233701, N'Asia', N'Asia', N'Western Asia');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (106, N'Italy', N'Italian Republic', N'ITA', 380, N'UN Member State', 60451260, N'Europe', N'Europe', N'Southern Europe');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (107, N'Jamaica', N'Jamaica', N'JAM', 388, N'UN Member State', 2825928, N'North America', N'Americas', N'Caribbean');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (108, N'Japan', N'Japan', N'JPN', 392, N'UN Member State', 127078679, N'Asia', N'Asia', N'Eastern Asia');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (110, N'Jordan', N'Hashemite Kingdom of Jordan', N'JOR', 400, N'UN Member State', 6342948, N'Asia', N'Asia', N'Western Asia');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (111, N'Kazakhstan', N'Republic of Kazakhstan', N'KAZ', 398, N'UN Member State', 15399437, N'Asia', N'Asia', N'Central Asia');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (112, N'Kenya', N'Republic of Kenya', N'KEN', 404, N'UN Member State', 40562882, N'Africa', N'Africa', N'Eastern Africa');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (113, N'Kiribati', N'Republic of Kiribati', N'KIR', 296, N'UN Member State', 112850, N'Oceania', N'Oceania', N'Micronesia');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (114, N'Korea', N'Republic of Korea', N'KOR', 410, N'UN Member State', 48508972, N'Asia', N'Asia', N'Eastern Asia');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (116, N'Kuwait', N'State of Kuwait', N'KWT', 414, N'UN Member State', 2691158, N'Asia', N'Asia', N'Western Asia');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (117, N'Kyrgyzstan', N'Kyrgyz Republic', N'KGZ', 417, N'UN Member State', 5431747, N'Asia', N'Asia', N'Central Asia');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (118, N'Lao PDR', N'Lao People''s Democratic Republic', N'LAO', 418, N'UN Member State', 7108339, N'Asia', N'Asia', N'South-Eastern Asia');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (119, N'Latvia', N'Republic of Latvia', N'LVA', 428, N'UN Member State', 2231503, N'Europe', N'Europe', N'Northern Europe');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (120, N'Lebanon', N'Lebanese Republic', N'LBN', 422, N'UN Member State', 4177778, N'Asia', N'Asia', N'Western Asia');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (121, N'Lesotho', N'Kingdom of Lesotho', N'LSO', 426, N'UN Member State', 2130819, N'Africa', N'Africa', N'Southern Africa');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (122, N'Liberia', N'Republic of Liberia', N'LBR', 430, N'UN Member State', 3441790, N'Africa', N'Africa', N'Western Africa');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (123, N'Libya', N'Libya', N'LBY', 434, N'UN Member State', 6310434, N'Africa', N'Africa', N'Northern Africa');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (124, N'Liechtenstein', N'Principality of Liechtenstein', N'LIE', 438, N'UN Member State', 34761, N'Europe', N'Europe', N'Western Europe');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (125, N'Lithuania', N'Republic of Lithuania', N'LTU', 440, N'UN Member State', 3697386, N'Europe', N'Europe', N'Northern Europe');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (126, N'Luxembourg', N'Grand Duchy of Luxembourg', N'LUX', 442, N'UN Member State', 491775, N'Europe', N'Europe', N'Western Europe');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (128, N'Macedonia', N'Former Yugoslav Republic of Macedonia', N'MKD', 807, N'UN Member State', 2149386, N'Europe', N'Europe', N'Southern Europe');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (129, N'Madagascar', N'Republic of Madagascar', N'MDG', 450, N'UN Member State', 20653556, N'Africa', N'Africa', N'Eastern Africa');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (130, N'Malawi', N'Republic of Malawi', N'MWI', 454, N'UN Member State', 14268711, N'Africa', N'Africa', N'Eastern Africa');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (131, N'Malaysia', N'Malaysia', N'MYS', 458, N'UN Member State', 25715819, N'Asia', N'Asia', N'South-Eastern Asia');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (132, N'Maldives', N'Republic of Maldives', N'MDV', 462, N'UN Member State', 396334, N'Seven seas (open ocean)', N'Asia', N'Southern Asia');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (133, N'Mali', N'Republic of Mali', N'MLI', 466, N'UN Member State', 12666987, N'Africa', N'Africa', N'Western Africa');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (134, N'Malta', N'Republic of Malta', N'MLT', 470, N'UN Member State', 421371, N'Europe', N'Europe', N'Southern Europe');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (135, N'Marshall Is.', N'Republic of the Marshall Islands', N'MHL', 584, N'UN Member State', 64522, N'Oceania', N'Oceania', N'Micronesia');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (136, N'Mauritania', N'Islamic Republic of Mauritania', N'MRT', 478, N'UN Member State', 3129486, N'Africa', N'Africa', N'Western Africa');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (137, N'Mauritius', N'Republic of Mauritius', N'MUS', 480, N'UN Member State', 1284264, N'Seven seas (open ocean)', N'Africa', N'Eastern Africa');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (138, N'Mexico', N'United Mexican States', N'MEX', 484, N'UN Member State', 111211789, N'North America', N'Americas', N'Central America');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (139, N'Micronesia', N'Federated States of Micronesia', N'FSM', 583, N'UN Member State', 107434, N'Oceania', N'Oceania', N'Micronesia');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (140, N'Moldova', N'Republic of Moldova', N'MDA', 498, N'UN Member State', 4320748, N'Europe', N'Europe', N'Eastern Europe');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (141, N'Monaco', N'Principality of Monaco', N'MCO', 492, N'UN Member State', 32965, N'Europe', N'Europe', N'Western Europe');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (142, N'Mongolia', N'Mongolia', N'MNG', 496, N'UN Member State', 3041142, N'Asia', N'Asia', N'Eastern Asia');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (143, N'Montenegro', N'Montenegro', N'MNE', 499, N'UN Member State', 672180, N'Europe', N'Europe', N'Southern Europe');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (145, N'Morocco', N'Kingdom of Morocco', N'MAR', 504, N'UN Member State', 34859364, N'Africa', N'Africa', N'Northern Africa');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (146, N'Mozambique', N'Republic of Mozambique', N'MOZ', 508, N'UN Member State', 21669278, N'Africa', N'Africa', N'Eastern Africa');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (147, N'Myanmar', N'Republic of the Union of Myanmar', N'MMR', 104, N'UN Member State', 48137741, N'Asia', N'Asia', N'South-Eastern Asia');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (150, N'Namibia', N'Republic of Namibia', N'NAM', 516, N'UN Member State', 2108665, N'Africa', N'Africa', N'Southern Africa');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (151, N'Nauru', N'Republic of Nauru', N'NRU', 520, N'UN Member State', 14019, N'Oceania', N'Oceania', N'Micronesia');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (152, N'Nepal', N'Nepal', N'NPL', 524, N'UN Member State', 29705912, N'Asia', N'Asia', N'Southern Asia');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (153, N'Netherlands', N'Kingdom of the Netherlands', N'NLD', 528, N'UN Member State', 16715999, N'Europe', N'Europe', N'Western Europe');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (155, N'New Zealand', N'New Zealand', N'NZL', 554, N'UN Member State', 4381954, N'Oceania', N'Oceania', N'Australia and New Zealand');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (156, N'Nicaragua', N'Republic of Nicaragua', N'NIC', 558, N'UN Member State', 5891199, N'North America', N'Americas', N'Central America');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (157, N'Niger', N'Republic of Niger', N'NER', 562, N'UN Member State', 15918502, N'Africa', N'Africa', N'Western Africa');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (158, N'Nigeria', N'Federal Republic of Nigeria', N'NGA', 566, N'UN Member State', 149229090, N'Africa', N'Africa', N'Western Africa');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (161, N'Norway', N'Kingdom of Norway', N'NOR', 578, N'UN Member State', 4676305, N'Europe', N'Europe', N'Northern Europe');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (162, N'Oman', N'Sultanate of Oman', N'OMN', 512, N'UN Member State', 3418085, N'Asia', N'Asia', N'Western Asia');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (163, N'Pakistan', N'Islamic Republic of Pakistan', N'PAK', 586, N'UN Member State', 176242949, N'Asia', N'Asia', N'Southern Asia');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (164, N'Palau', N'Republic of Palau', N'PLW', 585, N'UN Member State', 20796, N'Oceania', N'Oceania', N'Micronesia');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (166, N'Panama', N'Republic of Panama', N'PAN', 591, N'UN Member State', 3360474, N'North America', N'Americas', N'Central America');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (167, N'Papua New Guinea', N'Independent State of Papua New Guinea', N'PNG', 598, N'UN Member State', 6057263, N'Oceania', N'Oceania', N'Melanesia');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (168, N'Paraguay', N'Republic of Paraguay', N'PRY', 600, N'UN Member State', 6995655, N'South America', N'Americas', N'South America');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (169, N'Peru', N'Republic of Peru', N'PER', 604, N'UN Member State', 29546963, N'South America', N'Americas', N'South America');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (170, N'Philippines', N'Republic of the Philippines', N'PHL', 608, N'UN Member State', 97976603, N'Asia', N'Asia', N'South-Eastern Asia');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (172, N'Poland', N'Republic of Poland', N'POL', 616, N'UN Member State', 40022235, N'Europe', N'Europe', N'Eastern Europe');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (173, N'Portugal', N'Portuguese Republic', N'PRT', 620, N'UN Member State', 10707924, N'Europe', N'Europe', N'Southern Europe');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (175, N'Qatar', N'State of Qatar', N'QAT', 634, N'UN Member State', 833285, N'Asia', N'Asia', N'Western Asia');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (176, N'Romania', N'Romania', N'ROU', 642, N'UN Member State', 22215421, N'Europe', N'Europe', N'Eastern Europe');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (177, N'Russia', N'Russian Federation', N'RUS', 643, N'UN Member State', 140041247, N'Europe', N'Europe', N'Eastern Europe');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (178, N'Rwanda', N'Republic of Rwanda', N'RWA', 646, N'UN Member State', 10473282, N'Africa', N'Africa', N'Eastern Africa');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (182, N'Saint Lucia', N'Saint Lucia', N'LCA', 662, N'UN Member State', 160267, N'North America', N'Americas', N'Caribbean');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (183, N'Samoa', N'Independent State of Samoa', N'WSM', 882, N'UN Member State', 228797, N'Oceania', N'Oceania', N'Polynesia');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (184, N'San Marino', N'Republic of San Marino', N'SMR', 674, N'UN Member State', 30324, N'Europe', N'Europe', N'Southern Europe');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (185, N'São Tomé and Principe', N'Democratic Republic of São Tomé and Principe', N'STP', 678, N'UN Member State', 212679, N'Africa', N'Africa', N'Middle Africa');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (186, N'Saudi Arabia', N'Kingdom of Saudi Arabia', N'SAU', 682, N'UN Member State', 28686633, N'Asia', N'Asia', N'Western Asia');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (187, N'Senegal', N'Republic of Senegal', N'SEN', 686, N'UN Member State', 13711597, N'Africa', N'Africa', N'Western Africa');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (188, N'Serbia', N'Republic of Serbia', N'SRB', 688, N'UN Member State', 7379339, N'Europe', N'Europe', N'Southern Europe');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (189, N'Seychelles', N'Republic of Seychelles', N'SYC', 690, N'UN Member State', 87476, N'Seven seas (open ocean)', N'Africa', N'Eastern Africa');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (191, N'Sierra Leone', N'Republic of Sierra Leone', N'SLE', 694, N'UN Member State', 6440053, N'Africa', N'Africa', N'Western Africa');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (192, N'Singapore', N'Republic of Singapore', N'SGP', 702, N'UN Member State', 4657542, N'Asia', N'Asia', N'South-Eastern Asia');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (194, N'Slovakia', N'Slovak Republic', N'SVK', 703, N'UN Member State', 5681567, N'Europe', N'Europe', N'Eastern Europe');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (195, N'Slovenia', N'Republic of Slovenia', N'SVN', 705, N'UN Member State', 2005692, N'Europe', N'Europe', N'Southern Europe');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (196, N'Solomon Is.', N'Solomon Is.', N'SLB', 90, N'UN Member State', 595613, N'Oceania', N'Oceania', N'Melanesia');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (197, N'Somalia', N'Federal Republic of Somalia', N'SOM', 706, N'UN Member State', 9832017, N'Africa', N'Africa', N'Eastern Africa');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (199, N'South Africa', N'Republic of South Africa', N'ZAF', 710, N'UN Member State', 49052489, N'Africa', N'Africa', N'Southern Africa');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (200, N'Spain', N'Kingdom of Spain', N'ESP', 724, N'UN Member State', 40525002, N'Europe', N'Europe', N'Southern Europe');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (201, N'Sri Lanka', N'Democratic Socialist Republic of Sri Lanka', N'LKA', 144, N'UN Member State', 21324791, N'Asia', N'Asia', N'Southern Asia');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (202, N'St. Kitts and Nevis', N'Federation of Saint Kitts and Nevis', N'KNA', 659, N'UN Member State', 40131, N'North America', N'Americas', N'Caribbean');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (204, N'St. Vin. and Gren.', N'Saint Vincent and the Grenadines', N'VCT', 670, N'UN Member State', 108756, N'North America', N'Americas', N'Caribbean');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (207, N'Sudan', N'Republic of the Sudan', N'SDN', 729, N'UN Member State', 25946220, N'Africa', N'Africa', N'Northern Africa');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (208, N'Suriname', N'Republic of Suriname', N'SUR', 740, N'UN Member State', 481267, N'South America', N'Americas', N'South America');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (209, N'Swaziland', N'Kingdom of Swaziland', N'SWZ', 748, N'UN Member State', 1168869, N'Africa', N'Africa', N'Southern Africa');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (210, N'Sweden', N'Kingdom of Sweden', N'SWE', 752, N'UN Member State', 9059651, N'Europe', N'Europe', N'Northern Europe');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (211, N'Switzerland', N'Swiss Confederation', N'CHE', 756, N'UN Member State', 7604467, N'Europe', N'Europe', N'Western Europe');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (212, N'Syria', N'Syrian Arab Republic', N'SYR', 760, N'UN Member State', 20178485, N'Asia', N'Asia', N'Western Asia');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (214, N'Tajikistan', N'Republic of Tajikistan', N'TJK', 762, N'UN Member State', 7349145, N'Asia', N'Asia', N'Central Asia');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (215, N'Tanzania', N'United Republic of Tanzania', N'TZA', 834, N'UN Member State', 41048532, N'Africa', N'Africa', N'Eastern Africa');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (216, N'Thailand', N'Kingdom of Thailand', N'THA', 764, N'UN Member State', 65905410, N'Asia', N'Asia', N'South-Eastern Asia');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (217, N'Timor-Leste', N'Democratic Republic of Timor-Leste', N'TLS', 626, N'UN Member State', 1131612, N'Asia', N'Asia', N'South-Eastern Asia');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (218, N'Togo', N'Togolese Republic', N'TGO', 768, N'UN Member State', 6019877, N'Africa', N'Africa', N'Western Africa');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (219, N'Tonga', N'Kingdom of Tonga', N'TON', 776, N'UN Member State', 125733, N'Oceania', N'Oceania', N'Polynesia');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (220, N'Trinidad and Tobago', N'Republic of Trinidad and Tobago', N'TTO', 780, N'UN Member State', 1310000, N'North America', N'Americas', N'Caribbean');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (221, N'Tunisia', N'Republic of Tunisia', N'TUN', 788, N'UN Member State', 10486339, N'Africa', N'Africa', N'Northern Africa');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (222, N'Turkey', N'Republic of Turkey', N'TUR', 792, N'UN Member State', 76805524, N'Asia', N'Asia', N'Western Asia');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (223, N'Turkmenistan', N'Turkmenistan', N'TKM', 795, N'UN Member State', 4884887, N'Asia', N'Asia', N'Central Asia');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (226, N'Uganda', N'Republic of Uganda', N'UGA', 800, N'UN Member State', 32369558, N'Africa', N'Africa', N'Eastern Africa');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (227, N'Ukraine', N'Ukraine', N'UKR', 804, N'UN Member State', 45700395, N'Europe', N'Europe', N'Eastern Europe');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (228, N'United Arab Emirates', N'United Arab Emirates', N'ARE', 784, N'UN Member State', 4798491, N'Asia', N'Asia', N'Western Asia');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (229, N'United Kingdom', N'United Kingdom of Great Britain and Northern Ireland', N'GBR', 826, N'UN Member State', 62262000, N'Europe', N'Europe', N'Northern Europe');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (230, N'United States', N'United States of America', N'USA', 840, N'UN Member State', 313973000, N'North America', N'Americas', N'Northern America');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (231, N'Uruguay', N'Oriental Republic of Uruguay', N'URY', 858, N'UN Member State', 3494382, N'South America', N'Americas', N'South America');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (232, N'Uzbekistan', N'Republic of Uzbekistan', N'UZB', 860, N'UN Member State', 27606007, N'Asia', N'Asia', N'Central Asia');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (233, N'Vanuatu', N'Republic of Vanuatu', N'VUT', 548, N'UN Member State', 218519, N'Oceania', N'Oceania', N'Melanesia');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (235, N'Venezuela', N'Bolivarian Republic of Venezuela', N'VEN', 862, N'UN Member State', 26814843, N'South America', N'Americas', N'South America');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (236, N'Vietnam', N'Socialist Republic of Vietnam', N'VNM', 704, N'UN Member State', 86967524, N'Asia', N'Asia', N'South-Eastern Asia');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (239, N'Yemen', N'Republic of Yemen', N'YEM', 887, N'UN Member State', 23822783, N'Asia', N'Asia', N'Western Asia');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (240, N'Zambia', N'Republic of Zambia', N'ZMB', 894, N'UN Member State', 11862740, N'Africa', N'Africa', N'Eastern Africa');

INSERT INTO COUNTRIES (COUNTRYID, COUNTRYNAME, FORMALNAME, ISOALPHA3CODE, ISONUMERICCODE, COUNTRYTYPE, LATESTRECORDEDPOPULATION, CONTINENT, REGION, SUBREGION) 
VALUES (241, N'Zimbabwe', N'Republic of Zimbabwe', N'ZWE', 716, N'UN Member State', 12619600, N'Africa', N'Africa', N'Eastern Africa');

