SET DEFINE OFF

INSERT INTO CUSTOMERCATEGORIES (CUSTOMERCATEGORYID, CUSTOMERCATEGORYNAME) 
VALUES (1, N'Agent');

INSERT INTO CUSTOMERCATEGORIES (CUSTOMERCATEGORYID, CUSTOMERCATEGORYNAME) 
VALUES (5, N'Computer Store');

INSERT INTO CUSTOMERCATEGORIES (CUSTOMERCATEGORYID, CUSTOMERCATEGORYNAME) 
VALUES (7, N'Corporate');

INSERT INTO CUSTOMERCATEGORIES (CUSTOMERCATEGORYID, CUSTOMERCATEGORYNAME) 
VALUES (8, N'General Retailer');

INSERT INTO CUSTOMERCATEGORIES (CUSTOMERCATEGORYID, CUSTOMERCATEGORYNAME) 
VALUES (6, N'Gift Store');

INSERT INTO CUSTOMERCATEGORIES (CUSTOMERCATEGORYID, CUSTOMERCATEGORYNAME) 
VALUES (3, N'Novelty Shop');

INSERT INTO CUSTOMERCATEGORIES (CUSTOMERCATEGORYID, CUSTOMERCATEGORYNAME) 
VALUES (4, N'Supermarket');

INSERT INTO CUSTOMERCATEGORIES (CUSTOMERCATEGORYID, CUSTOMERCATEGORYNAME) 
VALUES (2, N'Wholesaler');

