SET DEFINE OFF

INSERT INTO STATEPROVINCES (STATEPROVINCEID, STATEPROVINCECODE, STATEPROVINCENAME, COUNTRYID, SALESTERRITORY, LATESTRECORDEDPOPULATION) 
VALUES (1, N'AL', N'Alabama', 230, N'Southeast', 5437278);

INSERT INTO STATEPROVINCES (STATEPROVINCEID, STATEPROVINCECODE, STATEPROVINCENAME, COUNTRYID, SALESTERRITORY, LATESTRECORDEDPOPULATION) 
VALUES (2, N'AK', N'Alaska', 230, N'Far West', 735132);

INSERT INTO STATEPROVINCES (STATEPROVINCEID, STATEPROVINCECODE, STATEPROVINCENAME, COUNTRYID, SALESTERRITORY, LATESTRECORDEDPOPULATION) 
VALUES (3, N'AZ', N'Arizona', 230, N'Southwest', 6891688);

INSERT INTO STATEPROVINCES (STATEPROVINCEID, STATEPROVINCECODE, STATEPROVINCENAME, COUNTRYID, SALESTERRITORY, LATESTRECORDEDPOPULATION) 
VALUES (4, N'AR', N'Arkansas', 230, N'Southeast', 3077747);

INSERT INTO STATEPROVINCES (STATEPROVINCEID, STATEPROVINCECODE, STATEPROVINCENAME, COUNTRYID, SALESTERRITORY, LATESTRECORDEDPOPULATION) 
VALUES (5, N'CA', N'California', 230, N'Far West', 41460453);

INSERT INTO STATEPROVINCES (STATEPROVINCEID, STATEPROVINCECODE, STATEPROVINCENAME, COUNTRYID, SALESTERRITORY, LATESTRECORDEDPOPULATION) 
VALUES (6, N'CO', N'Colorado', 230, N'Rocky Mountain', 5698265);

INSERT INTO STATEPROVINCES (STATEPROVINCEID, STATEPROVINCECODE, STATEPROVINCENAME, COUNTRYID, SALESTERRITORY, LATESTRECORDEDPOPULATION) 
VALUES (7, N'CT', N'Connecticut', 230, N'New England', 3739923);

INSERT INTO STATEPROVINCES (STATEPROVINCEID, STATEPROVINCECODE, STATEPROVINCENAME, COUNTRYID, SALESTERRITORY, LATESTRECORDEDPOPULATION) 
VALUES (8, N'DE', N'Delaware', 230, N'Mideast', 1001289);

INSERT INTO STATEPROVINCES (STATEPROVINCEID, STATEPROVINCECODE, STATEPROVINCENAME, COUNTRYID, SALESTERRITORY, LATESTRECORDEDPOPULATION) 
VALUES (9, N'DC', N'District of Columbia', 230, N'Mideast', 685248);

INSERT INTO STATEPROVINCES (STATEPROVINCEID, STATEPROVINCECODE, STATEPROVINCENAME, COUNTRYID, SALESTERRITORY, LATESTRECORDEDPOPULATION) 
VALUES (10, N'FL', N'Florida', 230, N'Southeast', 21148372);

INSERT INTO STATEPROVINCES (STATEPROVINCEID, STATEPROVINCECODE, STATEPROVINCENAME, COUNTRYID, SALESTERRITORY, LATESTRECORDEDPOPULATION) 
VALUES (11, N'GA', N'Georgia', 230, N'Southeast', 9992167);

INSERT INTO STATEPROVINCES (STATEPROVINCEID, STATEPROVINCECODE, STATEPROVINCENAME, COUNTRYID, SALESTERRITORY, LATESTRECORDEDPOPULATION) 
VALUES (12, N'HI', N'Hawaii', 230, N'Far West', 1404054);

INSERT INTO STATEPROVINCES (STATEPROVINCEID, STATEPROVINCECODE, STATEPROVINCENAME, COUNTRYID, SALESTERRITORY, LATESTRECORDEDPOPULATION) 
VALUES (13, N'ID', N'Idaho', 230, N'Rocky Mountain', 1612136);

INSERT INTO STATEPROVINCES (STATEPROVINCEID, STATEPROVINCECODE, STATEPROVINCENAME, COUNTRYID, SALESTERRITORY, LATESTRECORDEDPOPULATION) 
VALUES (14, N'IL', N'Illinois', 230, N'Great Lakes', 13397420);

INSERT INTO STATEPROVINCES (STATEPROVINCEID, STATEPROVINCECODE, STATEPROVINCENAME, COUNTRYID, SALESTERRITORY, LATESTRECORDEDPOPULATION) 
VALUES (15, N'IN', N'Indiana', 230, N'Great Lakes', 6570902);

INSERT INTO STATEPROVINCES (STATEPROVINCEID, STATEPROVINCECODE, STATEPROVINCENAME, COUNTRYID, SALESTERRITORY, LATESTRECORDEDPOPULATION) 
VALUES (16, N'IA', N'Iowa', 230, N'Plains', 3214032);

INSERT INTO STATEPROVINCES (STATEPROVINCEID, STATEPROVINCECODE, STATEPROVINCENAME, COUNTRYID, SALESTERRITORY, LATESTRECORDEDPOPULATION) 
VALUES (17, N'KS', N'Kansas', 230, N'Plains', 2893957);

INSERT INTO STATEPROVINCES (STATEPROVINCEID, STATEPROVINCECODE, STATEPROVINCENAME, COUNTRYID, SALESTERRITORY, LATESTRECORDEDPOPULATION) 
VALUES (18, N'KY', N'Kentucky', 230, N'Southeast', 4571106);

INSERT INTO STATEPROVINCES (STATEPROVINCEID, STATEPROVINCECODE, STATEPROVINCENAME, COUNTRYID, SALESTERRITORY, LATESTRECORDEDPOPULATION) 
VALUES (19, N'LA', N'Louisiana', 230, N'Southeast', 4810488);

INSERT INTO STATEPROVINCES (STATEPROVINCEID, STATEPROVINCECODE, STATEPROVINCENAME, COUNTRYID, SALESTERRITORY, LATESTRECORDEDPOPULATION) 
VALUES (20, N'ME', N'Maine', 230, N'New England', 1381434);

INSERT INTO STATEPROVINCES (STATEPROVINCEID, STATEPROVINCECODE, STATEPROVINCENAME, COUNTRYID, SALESTERRITORY, LATESTRECORDEDPOPULATION) 
VALUES (21, N'MD', N'Maryland', 230, N'Mideast', 5928814);

INSERT INTO STATEPROVINCES (STATEPROVINCEID, STATEPROVINCECODE, STATEPROVINCENAME, COUNTRYID, SALESTERRITORY, LATESTRECORDEDPOPULATION) 
VALUES (22, N'MA', N'Massachusetts[E]', 230, N'New England', 6960536);

INSERT INTO STATEPROVINCES (STATEPROVINCEID, STATEPROVINCECODE, STATEPROVINCENAME, COUNTRYID, SALESTERRITORY, LATESTRECORDEDPOPULATION) 
VALUES (23, N'MI', N'Michigan', 230, N'Great Lakes', 9895622);

INSERT INTO STATEPROVINCES (STATEPROVINCEID, STATEPROVINCECODE, STATEPROVINCENAME, COUNTRYID, SALESTERRITORY, LATESTRECORDEDPOPULATION) 
VALUES (24, N'MN', N'Minnesota', 230, N'Plains', 5637195);

INSERT INTO STATEPROVINCES (STATEPROVINCEID, STATEPROVINCECODE, STATEPROVINCENAME, COUNTRYID, SALESTERRITORY, LATESTRECORDEDPOPULATION) 
VALUES (25, N'MS', N'Mississippi', 230, N'Southeast', 2991207);

INSERT INTO STATEPROVINCES (STATEPROVINCEID, STATEPROVINCECODE, STATEPROVINCENAME, COUNTRYID, SALESTERRITORY, LATESTRECORDEDPOPULATION) 
VALUES (26, N'MO', N'Missouri', 230, N'Plains', 6262867);

INSERT INTO STATEPROVINCES (STATEPROVINCEID, STATEPROVINCECODE, STATEPROVINCENAME, COUNTRYID, SALESTERRITORY, LATESTRECORDEDPOPULATION) 
VALUES (27, N'MT', N'Montana', 230, N'Rocky Mountain', 1187597);

INSERT INTO STATEPROVINCES (STATEPROVINCEID, STATEPROVINCECODE, STATEPROVINCENAME, COUNTRYID, SALESTERRITORY, LATESTRECORDEDPOPULATION) 
VALUES (28, N'NE', N'Nebraska', 230, N'Plains', 1943256);

INSERT INTO STATEPROVINCES (STATEPROVINCEID, STATEPROVINCECODE, STATEPROVINCENAME, COUNTRYID, SALESTERRITORY, LATESTRECORDEDPOPULATION) 
VALUES (29, N'NV', N'Nevada', 230, N'Far West', 2790136);

INSERT INTO STATEPROVINCES (STATEPROVINCEID, STATEPROVINCECODE, STATEPROVINCENAME, COUNTRYID, SALESTERRITORY, LATESTRECORDEDPOPULATION) 
VALUES (30, N'NH', N'New Hampshire', 230, N'New England', 1376397);

INSERT INTO STATEPROVINCES (STATEPROVINCEID, STATEPROVINCECODE, STATEPROVINCENAME, COUNTRYID, SALESTERRITORY, LATESTRECORDEDPOPULATION) 
VALUES (31, N'NJ', N'New Jersey', 230, N'Mideast', 8899339);

INSERT INTO STATEPROVINCES (STATEPROVINCEID, STATEPROVINCECODE, STATEPROVINCENAME, COUNTRYID, SALESTERRITORY, LATESTRECORDEDPOPULATION) 
VALUES (32, N'NM', N'New Mexico', 230, N'Southwest', 2345662);

INSERT INTO STATEPROVINCES (STATEPROVINCEID, STATEPROVINCECODE, STATEPROVINCENAME, COUNTRYID, SALESTERRITORY, LATESTRECORDEDPOPULATION) 
VALUES (33, N'NY', N'New York', 230, N'Mideast', 20437172);

INSERT INTO STATEPROVINCES (STATEPROVINCEID, STATEPROVINCECODE, STATEPROVINCENAME, COUNTRYID, SALESTERRITORY, LATESTRECORDEDPOPULATION) 
VALUES (34, N'NC', N'North Carolina', 230, N'Southeast', 10241982);

INSERT INTO STATEPROVINCES (STATEPROVINCEID, STATEPROVINCECODE, STATEPROVINCENAME, COUNTRYID, SALESTERRITORY, LATESTRECORDEDPOPULATION) 
VALUES (35, N'ND', N'North Dakota', 230, N'Plains', 723393);

INSERT INTO STATEPROVINCES (STATEPROVINCEID, STATEPROVINCECODE, STATEPROVINCENAME, COUNTRYID, SALESTERRITORY, LATESTRECORDEDPOPULATION) 
VALUES (36, N'OH', N'Ohio', 230, N'Great Lakes', 12514985);

INSERT INTO STATEPROVINCES (STATEPROVINCEID, STATEPROVINCECODE, STATEPROVINCENAME, COUNTRYID, SALESTERRITORY, LATESTRECORDEDPOPULATION) 
VALUES (37, N'OK', N'Oklahoma', 230, N'Southwest', 3850568);

INSERT INTO STATEPROVINCES (STATEPROVINCEID, STATEPROVINCECODE, STATEPROVINCENAME, COUNTRYID, SALESTERRITORY, LATESTRECORDEDPOPULATION) 
VALUES (38, N'OR', N'Oregon', 230, N'Far West', 4250757);

INSERT INTO STATEPROVINCES (STATEPROVINCEID, STATEPROVINCECODE, STATEPROVINCENAME, COUNTRYID, SALESTERRITORY, LATESTRECORDEDPOPULATION) 
VALUES (39, N'PA', N'Pennsylvania', 230, N'Mideast', 13284753);

INSERT INTO STATEPROVINCES (STATEPROVINCEID, STATEPROVINCECODE, STATEPROVINCENAME, COUNTRYID, SALESTERRITORY, LATESTRECORDEDPOPULATION) 
VALUES (40, N'PR', N'Puerto Rico (US Territory)', 230, N'External', 3613149);

INSERT INTO STATEPROVINCES (STATEPROVINCEID, STATEPROVINCECODE, STATEPROVINCENAME, COUNTRYID, SALESTERRITORY, LATESTRECORDEDPOPULATION) 
VALUES (41, N'RI', N'Rhode Island', 230, N'New England', 1051511);

INSERT INTO STATEPROVINCES (STATEPROVINCEID, STATEPROVINCECODE, STATEPROVINCENAME, COUNTRYID, SALESTERRITORY, LATESTRECORDEDPOPULATION) 
VALUES (42, N'SC', N'South Carolina', 230, N'Southeast', 4774839);

INSERT INTO STATEPROVINCES (STATEPROVINCEID, STATEPROVINCECODE, STATEPROVINCENAME, COUNTRYID, SALESTERRITORY, LATESTRECORDEDPOPULATION) 
VALUES (43, N'SD', N'South Dakota', 230, N'Plains', 844877);

INSERT INTO STATEPROVINCES (STATEPROVINCEID, STATEPROVINCECODE, STATEPROVINCENAME, COUNTRYID, SALESTERRITORY, LATESTRECORDEDPOPULATION) 
VALUES (44, N'TN', N'Tennessee', 230, N'Southeast', 6495978);

INSERT INTO STATEPROVINCES (STATEPROVINCEID, STATEPROVINCECODE, STATEPROVINCENAME, COUNTRYID, SALESTERRITORY, LATESTRECORDEDPOPULATION) 
VALUES (45, N'TX', N'Texas', 230, N'Southwest', 27506120);

INSERT INTO STATEPROVINCES (STATEPROVINCEID, STATEPROVINCECODE, STATEPROVINCENAME, COUNTRYID, SALESTERRITORY, LATESTRECORDEDPOPULATION) 
VALUES (46, N'UT', N'Utah', 230, N'Rocky Mountain', 3016906);

INSERT INTO STATEPROVINCES (STATEPROVINCEID, STATEPROVINCECODE, STATEPROVINCENAME, COUNTRYID, SALESTERRITORY, LATESTRECORDEDPOPULATION) 
VALUES (47, N'VT', N'Vermont', 230, N'New England', 677762);

INSERT INTO STATEPROVINCES (STATEPROVINCEID, STATEPROVINCECODE, STATEPROVINCENAME, COUNTRYID, SALESTERRITORY, LATESTRECORDEDPOPULATION) 
VALUES (48, N'VI', N'Virgin Islands (US Territory)', 230, N'External', 104737);

INSERT INTO STATEPROVINCES (STATEPROVINCEID, STATEPROVINCECODE, STATEPROVINCENAME, COUNTRYID, SALESTERRITORY, LATESTRECORDEDPOPULATION) 
VALUES (49, N'VA', N'Virginia', 230, N'Southeast', 8260405);

INSERT INTO STATEPROVINCES (STATEPROVINCEID, STATEPROVINCECODE, STATEPROVINCENAME, COUNTRYID, SALESTERRITORY, LATESTRECORDEDPOPULATION) 
VALUES (50, N'WA', N'Washington', 230, N'Far West', 7540272);

INSERT INTO STATEPROVINCES (STATEPROVINCEID, STATEPROVINCECODE, STATEPROVINCENAME, COUNTRYID, SALESTERRITORY, LATESTRECORDEDPOPULATION) 
VALUES (51, N'WV', N'West Virginia', 230, N'Southeast', 2085839);

INSERT INTO STATEPROVINCES (STATEPROVINCEID, STATEPROVINCECODE, STATEPROVINCENAME, COUNTRYID, SALESTERRITORY, LATESTRECORDEDPOPULATION) 
VALUES (52, N'WI', N'Wisconsin', 230, N'Great Lakes', 6211317);

INSERT INTO STATEPROVINCES (STATEPROVINCEID, STATEPROVINCECODE, STATEPROVINCENAME, COUNTRYID, SALESTERRITORY, LATESTRECORDEDPOPULATION) 
VALUES (53, N'WY', N'Wyoming', 230, N'Rocky Mountain', 605964);

