SET DEFINE OFF

INSERT INTO SUPPLIERCATEGORIES (SUPPLIERCATEGORYID, SUPPLIERCATEGORYNAME) 
VALUES (4, N'Clothing Supplier');

INSERT INTO SUPPLIERCATEGORIES (SUPPLIERCATEGORYID, SUPPLIERCATEGORYNAME) 
VALUES (6, N'Courier Services Supplier');

INSERT INTO SUPPLIERCATEGORIES (SUPPLIERCATEGORYID, SUPPLIERCATEGORYNAME) 
VALUES (7, N'Financial Services Supplier');

INSERT INTO SUPPLIERCATEGORIES (SUPPLIERCATEGORYID, SUPPLIERCATEGORYNAME) 
VALUES (9, N'Insurance Services Supplier');

INSERT INTO SUPPLIERCATEGORIES (SUPPLIERCATEGORYID, SUPPLIERCATEGORYNAME) 
VALUES (8, N'Marketing Services Supplier');

INSERT INTO SUPPLIERCATEGORIES (SUPPLIERCATEGORYID, SUPPLIERCATEGORYNAME) 
VALUES (2, N'Novelty Goods Supplier');

INSERT INTO SUPPLIERCATEGORIES (SUPPLIERCATEGORYID, SUPPLIERCATEGORYNAME) 
VALUES (1, N'Other Wholesaler');

INSERT INTO SUPPLIERCATEGORIES (SUPPLIERCATEGORYID, SUPPLIERCATEGORYNAME) 
VALUES (5, N'Packaging Supplier');

INSERT INTO SUPPLIERCATEGORIES (SUPPLIERCATEGORYID, SUPPLIERCATEGORYNAME) 
VALUES (3, N'Toy Supplier');

