SET DEFINE OFF

INSERT INTO COLORS (COLORID, COLORNAME) 
VALUES (1, N'Azure');

INSERT INTO COLORS (COLORID, COLORNAME) 
VALUES (2, N'Beige');

INSERT INTO COLORS (COLORID, COLORNAME) 
VALUES (3, N'Black');

INSERT INTO COLORS (COLORID, COLORNAME) 
VALUES (4, N'Blue');

INSERT INTO COLORS (COLORID, COLORNAME) 
VALUES (5, N'Charcoal');

INSERT INTO COLORS (COLORID, COLORNAME) 
VALUES (6, N'Chartreuse');

INSERT INTO COLORS (COLORID, COLORNAME) 
VALUES (7, N'Cyan');

INSERT INTO COLORS (COLORID, COLORNAME) 
VALUES (8, N'Dark Brown');

INSERT INTO COLORS (COLORID, COLORNAME) 
VALUES (9, N'Dark Green');

INSERT INTO COLORS (COLORID, COLORNAME) 
VALUES (10, N'Fuchsia');

INSERT INTO COLORS (COLORID, COLORNAME) 
VALUES (11, N'Gold');

INSERT INTO COLORS (COLORID, COLORNAME) 
VALUES (13, N'Hot Pink');

INSERT INTO COLORS (COLORID, COLORNAME) 
VALUES (14, N'Indigo');

INSERT INTO COLORS (COLORID, COLORNAME) 
VALUES (15, N'Ivory');

INSERT INTO COLORS (COLORID, COLORNAME) 
VALUES (16, N'Khaki');

INSERT INTO COLORS (COLORID, COLORNAME) 
VALUES (17, N'Lavender');

INSERT INTO COLORS (COLORID, COLORNAME) 
VALUES (18, N'Light Brown');

INSERT INTO COLORS (COLORID, COLORNAME) 
VALUES (19, N'Light Green');

INSERT INTO COLORS (COLORID, COLORNAME) 
VALUES (20, N'Maroon');

INSERT INTO COLORS (COLORID, COLORNAME) 
VALUES (21, N'Mauve');

INSERT INTO COLORS (COLORID, COLORNAME) 
VALUES (22, N'Navy Blue');

INSERT INTO COLORS (COLORID, COLORNAME) 
VALUES (23, N'Olive');

INSERT INTO COLORS (COLORID, COLORNAME) 
VALUES (24, N'Orange');

INSERT INTO COLORS (COLORID, COLORNAME) 
VALUES (25, N'Plum');

INSERT INTO COLORS (COLORID, COLORNAME) 
VALUES (26, N'Puce');

INSERT INTO COLORS (COLORID, COLORNAME) 
VALUES (27, N'Purple');

INSERT INTO COLORS (COLORID, COLORNAME) 
VALUES (28, N'Red');

INSERT INTO COLORS (COLORID, COLORNAME) 
VALUES (29, N'Royal Blue');

INSERT INTO COLORS (COLORID, COLORNAME) 
VALUES (30, N'Salmon');

INSERT INTO COLORS (COLORID, COLORNAME) 
VALUES (31, N'Silver');

INSERT INTO COLORS (COLORID, COLORNAME) 
VALUES (12, N'Steel Gray');

INSERT INTO COLORS (COLORID, COLORNAME) 
VALUES (32, N'Tan');

INSERT INTO COLORS (COLORID, COLORNAME) 
VALUES (33, N'Teal');

INSERT INTO COLORS (COLORID, COLORNAME) 
VALUES (34, N'Wheat');

INSERT INTO COLORS (COLORID, COLORNAME) 
VALUES (35, N'White');

INSERT INTO COLORS (COLORID, COLORNAME) 
VALUES (36, N'Yellow');

